### ISSUE TITLE
helia mazinani

### ISSUE THREAD

**Issue by heliamazinani** [rezasharifi82/Fundamentals-of-programming#4]
![Screenshot (3)](https://user-images.githubusercontent.com/123804298/216706653-7acaa626-46a9-46ff-b900-57c8e237426b.png)
![Screenshot (4)](https://user-images.githubusercontent.com/123804298/216706712-eb5d1b94-97c3-4a3b-a70b-7653c52acf40.png)
![Screenshot (5)](https://user-images.githubusercontent.com/123804298/216706804-90888b2f-e2de-4a41-b0dd-8a33541261ba.png)
![Screenshot (7)](https://user-images.githubusercontent.com/123804298/216706895-db161da5-af81-4deb-bd9d-e2745703fd45.png)
![Screenshot (6)](https://user-images.githubusercontent.com/123804298/216707074-2b3d55e7-576b-4719-a4ef-429a086cc6b2.png)
![Screenshot (8)](https://user-images.githubusercontent.com/123804298/216707182-38c3d1e3-633e-4b84-be5b-a9dc1c8fe190.png)
![Screenshot (9)](https://user-images.githubusercontent.com/123804298/216707534-afd2b846-960a-49ef-8376-a73c32a8a627.png)
![Screenshot (10)](https://user-images.githubusercontent.com/123804298/216707647-533387fb-172e-4376-835c-3fe8b68914ec.png)
![Screenshot (11)](https://user-images.githubusercontent.com/123804298/216707715-c6f3ba44-a7c8-4b0e-b7bf-284693685ddf.png)
![Screenshot (12)](https://user-images.githubusercontent.com/123804298/216707785-b80afc2d-0b35-4d8d-86d7-4d029bca4dc0.png)
![Screenshot (14)](https://user-images.githubusercontent.com/123804298/216707906-c2338331-59e4-4670-aa1c-8cbab0244e4f.png)
![Screenshot (15)](https://user-images.githubusercontent.com/123804298/216708073-340e1989-a1d9-44c7-863f-2dc443cfc01b.png)
![Screenshot (16)](https://user-images.githubusercontent.com/123804298/216708195-49df6cba-ecbb-4abc-a6f7-3751abd46313.png)
![Screenshot (17)](https://user-images.githubusercontent.com/123804298/216708263-369dba4c-cdd7-404e-9cf4-7fedf6e3a52e.png)
![Screenshot (22)](https://user-images.githubusercontent.com/123804298/216709418-6b5ad770-310c-4841-a0de-7396383d4f8b.png)
![Screenshot (20)](https://user-images.githubusercontent.com/123804298/216710023-6ed5e9cf-0b4b-4b80-bee6-08f62efee5e9.png)

**Comment by amirr-kdm** [comment]
👎🏻👎🏻👎🏻👎🏻
