### ISSUE TITLE
MITM

### ISSUE THREAD

**Issue by AliRje82** [rezasharifi82/Fundamentals-of-programming#6]
ali rajaei
amirreza khadempir
https://github.com/AliRje82/MITM

![1](https://user-images.githubusercontent.com/121222311/216757153-7fd1ad11-d64c-4934-8a4c-3d64714b7b9d.JPG)
![2](https://user-images.githubusercontent.com/121222311/216757157-9996f10e-88de-4e40-a91a-089ae1d0a378.JPG)
![6](https://user-images.githubusercontent.com/121222311/216757160-95a3a8ec-3606-4f12-9291-3f8bc3fdfedb.JPG)
![3](https://user-images.githubusercontent.com/121222311/216757171-955c6393-5f01-4734-9f68-f3bf0da4fa3d.JPG)
![5](https://user-images.githubusercontent.com/121222311/216757181-02520715-e1ad-4ef9-a26f-08e0ba3352b3.JPG)

![4](https://user-images.githubusercontent.com/121222311/216757177-b245bda9-94b4-4ced-8fd3-9daa8bee6d1e.JPG)

**Comment by amirr-kdm** [comment]
🔥🔥🔥🔥🔥🔥🔥

**Comment by amirr-kdm** [comment]
The best game in the world😭😭😭😭🥹😱😱

**Comment by amirr-kdm** [comment]
این پروژه باید ۳۰۰ بگیرع

**Comment by heliamazinani** [comment]
buggy my boat keeps crashing an iceberg 
![802C88CD-5B9E-4DD5-AC1B-19C074C756EB](https://user-images.githubusercontent.com/123804298/216788028-804c945e-c1ac-49df-b5a4-bdfd21f6c80c.png)
![7E982773-B389-4A68-ABAB-CC8BB9447B37](https://user-images.githubusercontent.com/123804298/216788033-d8183055-a6e2-4352-a969-fa9a89ee2089.png)
