### ISSUE TITLE
project one

### ISSUE THREAD

**Issue by faezebg** [rezasharifi82/Fundamentals-of-programming#7]
zahra alipour
 faeze bagherian
https://github.com/tikcus1/faz-0.git
![Screenshot_20230203_095940](https://user-images.githubusercontent.com/120382002/216779209-d7e9ad1e-1d0f-4ad0-abd2-733c0291183a.png)
![win1](https://user-images.git
![win111](https://user-images.githubusercontent.com/120382002/216780496-2dcac068-ddee-4d3f-ac5e-fb1ca266ba51.jpg)
hubusercontent.com/120382002/216779741-104ebab2-fc3f-41c3-93a8-38d6dc2c3c4d.jpg)
![Screenshot_20230203_100407](https://user-images.githubusercontent.com/120382002/216779762-5d1797b7-eedf-49d3-bd89-6c351c4d721b.png)
![win2](https://user-images.githubusercontent.com/120382002/216779775-173dafb9-fbe1-4cf9-a1aa-a0889658804d.jpg)
![Screenshot_20230203_100124](https://user-images.githubusercontent.com/120382002/216779781-06cb8d35-5289-426b-83b3-e4b0da139e9d.png)
![close](https://user-images.githubusercontent.com/120382002/216779787-d5629607-3eeb-4e8d-9e4e-e3db4d063526.jpg)

**Comment by amirr-kdm** [comment]
جالب بود خخ

**Comment by amirr-kdm** [comment]
🔥🔥🔥🔥🔥🔥

**Comment by amirr-kdm** [comment]
⚡️⚡️⚡️⚡️⚡️⚡️

**Comment by amirr-kdm** [comment]
😱😱😱🔥🔥🔥

**Comment by amirr-kdm** [comment]
The best game in the world🔥🔥🔥🔥

**Comment by amirr-kdm** [comment]
این خونه رو کی ساخته؟

**Comment by faezebg** [comment]
اوستای بنا ساخته

**Comment by amirr-kdm** [comment]
> اوستای بنا ساخته

با چوب نعنا ساخته

**Comment by faezebg** [comment]
تهنای تهنا ساخته

**Comment by tikcus1** [comment]
دیوه اومد

**Comment by amirr-kdm** [comment]
> دیوه اومد

شما؟

**Comment by faezebg** [comment]
دیوه اومد
دیوه اومد
دیوه اومد

**Comment by tikcus1** [comment]
> دیوه اومد دیوه اومد دیوه اومد

کدوم دیو

**Comment by amirr-kdm** [comment]
کامنتا به دو کا برسه قرعه کشی iPhone 14 pro max میزاریم😱😱😱😱😱😱
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by faezebg** [comment]
همون دیوی که توی خواب بود

**Comment by tikcus1** [comment]
> 



> همون دیوی که توی خواب بود

کدوم خواب

**Comment by faezebg** [comment]
همون خوابی که تو چشاته

**Comment by tikcus1** [comment]
> همون خوابی که تو چشاته

کدوم چش

**Comment by amirr-kdm** [comment]
![Uploading 6F64EC56-9833-49BC-9313-29B6959D40B1.jpeg…]()

**Comment by faezebg** [comment]
همون چشمی که روزو گم کرد

**Comment by tikcus1** [comment]
:(

**Comment by amirr-kdm** [comment]
ایا ازین بازی اشغال خسته شدید؟
بزن رو لینک زیر😱😱
https://github.com/rezasharifi82/Fundamentals-of-programming/issues/6

**Comment by tikcus1** [comment]
🤡

> ایا ازین بازی اشغال خسته شدید؟ بزن رو لینک زیر😱😱 #6

**Comment by faezebg** [comment]
https://user-images.githubusercontent.com/120382002/216781812-458bbe89-c8cc-4110-8828-098b4d8b6b8e.mp4

**Comment by faezebg** [comment]
https://user-images.githubusercontent.com/120382002/216781909-7655d94b-db42-4812-b3e7-50950e1c5a00.mp4

**Comment by heliamazinani** [comment]
sold two kidneys for the premium version . worth it👍100/10
